# Generated by Django 4.1.3 on 2024-10-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_confirmed_alter_order_tax_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
    ]
