# Generated by Django 4.1.3 on 2024-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_reservations_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservations",
            name="total",
            field=models.FloatField(default=0),
        ),
    ]
