# Generated by Django 4.1.3 on 2024-10-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0004_table'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmbreofpeople', models.PositiveIntegerField(default=1)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'CANCELLED'), (3, 'DONE')], default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_reservation', to='accounts.userprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_reservation', to='vendor.vendor')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_reservation', to='vendor.table')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservation',
            },
        ),
    ]
