# Generated by Django 4.1.3 on 2024-11-09 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reservations",
        ),
    ]
