# Generated by Django 4.1.3 on 2024-10-21 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="longitude",
        ),
    ]
